# frozen_string_literal: true

DECIDIM_VERSION = { git: "https://github.com/decidim/decidim.git", branch: "develop" }

gem "decidim", DECIDIM_VERSION
gem "decidim-dev", DECIDIM_VERSION
gem "decidim-initiatives", DECIDIM_VERSION
gem "decidim-conferences", DECIDIM_VERSION
gem "decidim-consultations", DECIDIM_VERSION
gem "decidim-elections", DECIDIM_VERSION
gem "decidim-templates", DECIDIM_VERSION

gem "ransack", "~> 2.1.1"
gem "rails", "~> 5.2.4"
gem "uglifier"
gem "sprockets"
gem "faker", "~> 2.14.0"
gem "puma"

group :development do
  gem "listen", "~> 3.2.0"
end
