# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION
DECIDIM_VERSION = { git: "https://github.com/decidim/decidim.git", branch: "develop" }

gem "puma", "~> 5"
gem "bootsnap", "~> 1.3"
gem "uglifier", "~> 4.1"
gem "decidim", DECIDIM_VERSION
gem "faker", "~> 2.14"

group :development do
  gem "listen", "~> 3.1"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
end
